import { getStemmer } from "../mod.ts";
import words from "../data/ro/words_short.json" assert { type: "json" };
import { assertEquals } from "https://deno.land/std@0.149.0/testing/asserts.ts";

Deno.test("Romanian", async () => {
  const stemmer = await getStemmer("romanian");
  const out = [];
  for (const word of words) {
    out.push(stemmer.stem(word));
  }

  assertEquals(out, [
    "a",
    "ab",
    "abajur",
    "abajur",
    "abandon",
    "abandon",
    "abat",
    "abat",
    "abat",
    "abater",
    "abat",
    "abăt",
    "abăt",
    "abătuţ",
    "abces",
    "aber",
    "aber",
    "aber",
    "aberat",
    "abi",
    "abil",
    "abil",
    "abil",
    "abil",
    "abil",
    "abneg",
    "abonament",
    "abrupt",
    "absent",
    "absent",
    "absent",
    "absenţ",
    "absenţ",
    "absenţ",
    "absol",
    "absol",
    "absol",
    "absol",
    "absol",
    "absol",
    "absoluţ",
    "absolv",
    "absolvenţ",
    "absolvenţ",
    "absolv",
    "absolv",
    "absolv",
    "absolv",
    "absolv",
    "absorb",
    "absorb",
    "absorb",
    "absorb",
    "absorb",
    "absorb",
    "absorbţ",
    "abstinent",
    "abstract",
    "abstract",
    "abstract",
    "abstractiz",
    "abstractiz",
    "abstractiz",
    "abstractiz",
    "abstracto",
    "abstracţ",
    "abstracţ",
    "abstract",
    "abstract",
    "abstrag",
    "absurd",
    "absurd",
    "absurd",
    "absurd",
    "absurd",
    "absurd",
    "absurd",
    "abţin",
    "abţin",
    "abţin",
    "abundent",
    "abundent",
    "abur",
    "abur",
    "abur",
    "abur",
    "abur",
    "abur",
    "abuz",
    "abuz",
    "abuz",
  ]);
});
